# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a numpy array with values ranging from 10 to 49

In [3]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [4]:
arr = np.ones((2,2), dtype=np.int)
arr

array([[1, 1],
       [1, 1]])

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
arr = np.ones((3,2), dtype=np.float)
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [6]:
X = np.ones((2,3), dtype=np.int)
arr = np.ones_like(X)
arr = np.ones(X.shape, dtype=X.dtype)
arr

array([[1, 1, 1],
       [1, 1, 1]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [7]:
X = np.arange(30, 40)
arr = np.zeros_like(X)
arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Create a numpy matrix of 4*4 integers, filled with fives.

In [8]:
arr = np.full((4,4), 5, dtype=np.int)
arr


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
X = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.float)
arr = np.ones_like(X) * 7
arr

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [11]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [12]:
arr = np.random.randint(1,10,3,dtype=np.int)
arr


array([5, 5, 1])

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [13]:
arr = np.random.uniform(size=(3,3,3))
arr


array([[[0.62756163, 0.48359028, 0.83103808],
        [0.63379012, 0.28592045, 0.09711192],
        [0.38791678, 0.25194417, 0.85752147]],

       [[0.42784808, 0.4554649 , 0.23302951],
        [0.28261712, 0.05948534, 0.62148834],
        [0.58138288, 0.192312  , 0.10797294]],

       [[0.28402701, 0.1149375 , 0.78579139],
        [0.84264938, 0.17661674, 0.56052467],
        [0.93888916, 0.98988261, 0.49432369]]])

### Given the X python list convert it to an Y numpy array

In [14]:
X = [1,2,3,4,5]
print(X, type(X))
Y = np.array(X)
print(Y, type(Y))



[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


### Given the X numpy array, make a copy and store it on Y.

In [15]:
X = np.arange(5)
print(X, id(X))
Y = X.copy()
print(Y, id(Y))
Y


[0 1 2 3 4] 140262821628304
[0 1 2 3 4] 140262821628384


array([0, 1, 2, 3, 4])

### Create a numpy array with numbers from 1 to 10

In [16]:
arr = np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a numpy array with the odd numbers between 1 to 10

In [17]:
arr = np.arange(1,11,2)
arr


array([1, 3, 5, 7, 9])

### Create a numpy array with numbers from 1 to 10, in descending order.

In [18]:
arr = np.arange(10,0,-1)
arr


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [19]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Show the memory size of the given Z numpy matrix

In [21]:
Z = np.arange(5)
Z.size * Z.itemsize


40

## Array indexation


### Given the X numpy array, show it's first element

In [24]:
X = np.array([[20,2,3], [4,5,6]])
X[0][0]


20

### Given the X numpy array, show it's last element

In [25]:
X = np.arange(9)
X[-1]


8

### Given the X numpy array, show it's first three elements

In [26]:
X = np.arange(9)
X[:3]


array([0, 1, 2])

### Given the X numpy array, show all middle elements

In [27]:
X = np.array(["A", "B", "C", "D", "E", "F"])
X[1:-1]


array(['B', 'C', 'D', 'E'], dtype='<U1')

### Given the X numpy array, show the elements in reverse position

In [28]:
X = np.array(["A", "B", "C", "D", "E", "F"])
X[::-1]


array(['F', 'E', 'D', 'C', 'B', 'A'], dtype='<U1')

### Given the X numpy array, show the elements in an odd position

In [36]:
X = np.array(["A", "B", "C", "D", "E", "F"])
X[1::2]


array(['B', 'D', 'F'], dtype='<U1')

### Given the X numpy matrix, show the first row elements

In [37]:
X = np.array([["A", "B", "C"], ["D", "E", "F"]])
X[0]


array(['A', 'B', 'C'], dtype='<U1')

### Given the X numpy matrix, show the last row elements

In [38]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[-1]

array(['G', 'H', 'I'], dtype='<U1')

### Given the X numpy matrix, show the first element on first row

In [39]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[0][0]


'A'

### Given the X numpy matrix, show the last element on last row

In [40]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[-1][-1]


'I'

### Given the X numpy matrix, show the middle row elements

In [44]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[1:-1, 1:-1]


array([['E']], dtype='<U1')

### Given the X numpy matrix, show the first two elements on the first two rows

In [45]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[:2, :2]


array([['A', 'B'],
       ['D', 'E']], dtype='<U1')

### Given the X numpy matrix, show the last two elements on the last two rows

In [46]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[-2:, -2:]


array([['E', 'F'],
       ['H', 'I']], dtype='<U1')

## Array manipulation


### Convert the given integer numpy array to float

In [48]:
arr = np.arange(9, dtype=np.int)
arr.astype(float)


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

### Reverse the given numpy array (first element becomes last)

In [51]:
arr = np.arange(9)
arr[::-1]


array([8, 7, 6, 5, 4, 3, 2, 1, 0])

### Order (sort) the given numpy array

In [61]:
arr = np.array([8,7,6,5,4,3,2,1,9])
a = np.sort(arr)
a



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Given the X numpy array, set the fifth element equal to 1

In [63]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1, 0])
X[4] = 1
X


array([8, 7, 6, 5, 1, 3, 2, 1, 0])

### Given the X numpy array, change the 50 with a 40

In [65]:
X = np.array([8, 7, 6, 40, 4, 3, 50, 50, 50])
X[X == 50] = 40
X



array([ 8,  7,  6, 40,  4,  3, 40, 40, 40])

### Given the X numpy matrix, change the last row with all 1

In [66]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[-1][:] = 1
X


array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['1', '1', '1']], dtype='<U1')

### Given the X numpy matrix, change the last item on the last row with a 0

In [67]:
X = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]])
X[-1][-1] = 0
X


array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', '0']], dtype='<U1')

### Given the X numpy matrix, add 5 to every element

In [70]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [73]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13])
X < 0


array([False,  True, False, False,  True, False, False, False])

### Given the X numpy array, get the negative elements

In [72]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13])
X[X < 0]


array([ -7, -10])

### Given the X numpy array, get numbers higher than 5

In [74]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13])
X[X > 5]

array([ 6,  8,  9, 11, 12, 13])

### Given the X numpy array, get numbers higher than the elements mean

In [77]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13, 1, 2])
X[X > X.mean()]


array([ 6,  8,  9, 11, 12, 13])

### Given the X numpy array, get numbers equal to 2 or 10

In [80]:
X = np.array([6,  -7,  10,  9, -10, 11, 12, 13, 2])
X[(X == 2) | (X == 10)]


array([10,  2])

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [84]:
def b(X):
  if (X[X == 0]).size > 0:
    return False
  return True

X = np.array([6,  -7,  8,  9, -10, 11, 12, 13, 0])
r = b(X)
r

False

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

### Given the X numpy array, return True if any of its elements is zero

In [88]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13, 0])
r = np.all(X != 0)
r

False

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [92]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13])
X.sum()


42

### Given the X numpy array, show the mean value of its elements

In [93]:
X = np.array([6,  -7,  8,  9, -10, 11, 12, 13])
X.mean()


5.25

### Given the X numpy matrix, show the sum of its columns

In [95]:
X = np.array([[6,  -7,  8],  [9, -10, 11], [12, 13, 14]])
X.sum(axis=0)


array([27, -4, 33])

### Given the X numpy matrix, show the mean value of its rows

In [96]:
X = np.array([[6,  -7,  8],  [9, -10, 11], [12, 13, 14]])
X.mean(axis=1)


array([ 2.33333333,  3.33333333, 13.        ])

### Given the X numpy array, show the max value of its elements

In [97]:
X = np.array([[6,  -7,  8],  [9, -10, 11], [12, 13, 14]])
X.max()


14